export enum EnumCharacteristic {
  UNDEFINED = 'UNDEFINED',
  DOMESTICATED = 'DOMESTICATED',
  DOMESTICATED_IN_PROGRESS = 'DOMESTICATED_IN_PROGRESS',
  TIMID = 'TIMID', //craintif
  DOMINANT = 'DOMINANT',
  SUBMISSIVE = 'SUBMISSIVE',
  OK_MALE = 'OK_MALE',
  OK_FEMALE = 'OK_FEMALE',
  OK_ALL = 'OK_ALL',
  OK_CAT = 'OK_CAT',
}
